# Generated by Django 5.1.2 on 2024-10-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('acontact', models.CharField(max_length=10)),
                ('aemail', models.EmailField(max_length=50)),
                ('astate', models.CharField(max_length=500)),
                ('aexp', models.CharField(max_length=50)),
                ('adegree', models.CharField(max_length=12)),
                ('ayear', models.CharField(max_length=12)),
            ],
        ),
    ]
